### ISSUE TITLE
Feature Request: Secure Power Terminal

### ISSUE THREAD

**Issue by ArmandVestibule** [notabadminer/UniversalCoinsMod#18]
Question: Have you considered implementing a secure owner-breakable block that operates as a passthrough for Redstone Flux power for a configurable fee? 

There's another mod that offers a block similar to this for their proprietary power system but one that offers similar functionality for the RF standard (and/or others).  Could be neat for some SMP worlds.

**Comment by notabadminer** [comment]
I have been considering it for some time now. I'm just not sure if it belongs in Universal Coins, or if another mod should be created. I have a tech mod that I started that I could update and add the block into.

As for the block, I was thinking of adding a wireless rf transmission block. The base and receiver blocks would be linked somehow. The base GUI would allow the owner to set rf cost or collect the coins. The receiver would have two GUI. The owner GUI would be the same as the base. The player GUI would allow payment for the rf used. Both blocks would have text rendered to display rf/t transmitted and total rf used since last payment.

**Comment by ArmandVestibule** [comment]
Wireless is a neat idea.  I had it in my head that, in conjunction with a mod such as SecurityCraft, the cabling could be kept secure but this eliminates dependencies on other mods for it to be useful.

My logic for it being in UC was only because of the already-present redstone block which (I assume since I haven't used it) did something similar and it just kind of meshes.

Either way, regardless of where that wireless RF block ends up, that does sound like a good idea!

**Comment by notabadminer** [comment]
feature added in 1.7.x-1.6.34+
